// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"golang-beginner-chap24/database"
	"golang-beginner-chap24/handlers"
	"golang-beginner-chap24/middleware"
	"golang-beginner-chap24/repositories"
	"golang-beginner-chap24/services"
	"golang-beginner-chap24/utils"
)

// Injectors from wire.go:

func InitializeOrderHandler() *handlers.OrderHandler {
	db := database.NewPostgresDB()
	logger := utils.IntiLogger()
	orderRepository := repositories.NewOrderRepository(db, logger)
	orderService := services.NewOrderService(orderRepository)
	orderHandler := handlers.NewOrderHandler(orderService, logger)
	return orderHandler
}

func InitializePaymentMethodHandler() *handlers.PaymentMethodHandler {
	db := database.NewPostgresDB()
	paymentMethodRepository := repositories.NewPaymentMethodRepository(db)
	paymentMethodService := services.NewPaymentMethodService(paymentMethodRepository)
	paymentMethodHandler := handlers.NewPaymentMethodHandler(paymentMethodService)
	return paymentMethodHandler
}

func IniitalMiddleware() *middleware.Middleware {
	logger := utils.IntiLogger()
	middlewareMiddleware := middleware.NewMiddleware(logger)
	return middlewareMiddleware
}

func InitializeOrderItemHandler() *handlers.OrderItemHandler {
	db := database.NewPostgresDB()
	logger := utils.IntiLogger()
	orderItemRepository := repositories.NewOrderItemRepo(db, logger)
	orderItemService := services.NewOrderItemService(orderItemRepository)
	orderItemHandler := handlers.NewOrderItemHandler(orderItemService, logger)
	return orderItemHandler
}

// wire.go:

var orderHandlerSet = wire.NewSet(database.NewPostgresDB, utils.IntiLogger, repositories.NewOrderRepository, services.NewOrderService, handlers.NewOrderHandler)

var paymentMethods = wire.NewSet(database.NewPostgresDB, repositories.NewPaymentMethodRepository, services.NewPaymentMethodService, handlers.NewPaymentMethodHandler)

var middlewareSet = wire.NewSet(utils.IntiLogger, middleware.NewMiddleware)

var orderItemSet = wire.NewSet(database.NewPostgresDB, utils.IntiLogger, repositories.NewOrderItemRepo, services.NewOrderItemService, handlers.NewOrderItemHandler)
