// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"golang-beginner-chap24/database"
	"golang-beginner-chap24/handlers"
	"golang-beginner-chap24/repositories"
	"golang-beginner-chap24/services"
)

// Injectors from wire.go:

func InitializeOrderHandler() *handlers.OrderHandler {
	db := database.NewPostgresDB()
	orderRepository := repositories.NewOrderRepository(db)
	orderService := services.NewOrderService(orderRepository)
	orderHandler := handlers.NewOrderHandler(orderService)
	return orderHandler
}

func InitializePaymentMethodHandler() *handlers.PaymentMethodHandler {
	db := database.NewPostgresDB()
	paymentMethodRepository := repositories.NewPaymentMethodRepository(db)
	paymentMethodService := services.NewPaymentMethodService(paymentMethodRepository)
	paymentMethodHandler := handlers.NewPaymentMethodHandler(paymentMethodService)
	return paymentMethodHandler
}

// wire.go:

var orderHandlerSet = wire.NewSet(database.NewPostgresDB, repositories.NewOrderRepository, services.NewOrderService, handlers.NewOrderHandler)

var paymentMethods = wire.NewSet(database.NewPostgresDB, repositories.NewPaymentMethodRepository, services.NewPaymentMethodService, handlers.NewPaymentMethodHandler)
